name: sabani_tech_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.1.0
  lottie: ^3.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - .env

flutter_gen:
  output: lib/src/core/assets/
  integrations:
    flutter_svg: true
    lottie: true
